### PR TITLE
add HEAD method

### PR DESCRIPTION
**Pull request by limhyungseok**
I want to use the HEAD method.

### CODE REVIEW

**Comment by mrtazz** [comment]
This is great! Thank you for submitting this pull request! It seems CI is failing on the linter with `source/connection.cc:378:  Redundant blank line at the end of a code block should be deleted.  [whitespace/blank_line] [3]`. Could you please make sure CI passes? Thanks!

**Comment by limhyungseok** [comment]
Hi~. I have fixed it. and add test case. please check it~

**Comment by mrtazz** [comment]
This looks great! Can you also document the usage in the [README](https://github.com/mrtazz/restclient-cpp/blob/master/README.md#usage)

**Comment by limhyungseok** [comment]
I have modified the README.md

**Comment by mrtazz** [comment]
merged! thank you for the contribution!

**Pull request closed without merging**
