### PR TITLE
Added support for progress reporting when downloading/uploading

### PR DESCRIPTION
**Pull request by lawmaestro**
## Checklist
Not all of these might apply to your change but the more you are able to check
the easier it will be to get your contribution merged.

- [x] CI passes
- [x] Description of proposed change
- [x] Documentation (README, code doc blocks, etc) is updated
- [x] Existing issue is referenced if there is one
- [x] Unit tests for the proposed change

### CODE REVIEW

**Comment by mrtazz** [comment]
Can you please make sure this change has unit tests, works on CI, and has an example usage documented in the README?

**Comment by mrtazz** [comment]
C11 support is fine to add I think. We have other places now that kinda need it anyways.

**Comment by lawmaestro** [comment]
> C11 support is fine to add I think. We have other places now that kinda need it anyways.

Looks like C11 support has been added for the test suite now :) I've merged in latest master & resolved the conflict. Let me know your thoughts 👍

**Comment by mrtazz** [comment]
perfect! thank you for the contribution!

**Pull request merged**
