### PR TITLE
add client cert & key support

### PR DESCRIPTION
**Pull request by bl4ck5un**
Allow users to specify client certs & keys by setting `CURLOPT_SSLCERT`, `CURLOPT_SSLCERTTYPE`, `CURLOPT_SSLKEY`.

### CODE REVIEW

**Comment by mrtazz** [comment]
The general pull request looks good, but can you please make sure CI passes on this?

**Comment by mrtazz** [comment]
Thanks for working on this! In order to keep the coverage up, I think I'm ok with the following test cases:

- set an existing client cert (you can generate one and commit it into `test/fixtures`)
- set a non-existing client cert and test for a valid error return code from the respective functions

**Comment by mrtazz** [comment]
hey @bl4ck5un, any update on whether you can find the time to add those code coverage tests?

**Comment by bl4ck5un** [comment]
@mrtazz Finally done.

**Comment by mrtazz** [comment]
oh awesome! Thank you for that. Is there a way to surface using a non-existing client cert to the user? It seems curl fails generic requests in that case. It would be nice to have some way of returning a more descriptive error when a non-existing/non-readable cert is used.

**Comment by bl4ck5un** [comment]
Good point. I added `curl_easy_strerror(res)` to return a descriptive message on certificate problems.

**Comment by mrtazz** [comment]
@bl4ck5un I restarted the CI job to see if it was an intermittent error. Given that the tests are mostly integration tests, connections to `httpbin.org` can be flaky. Rarely but it does happen

**Comment by bl4ck5un** [comment]
@mrtazz I think I found it. When built against `libcurl4-gnutls-dev`, I can reproduce the same error locally. But building against `libcurl4-openssl-dev` is fine. Maybe you can change the travis file to use the latter? That looks like a bug in GnuTLS to me.

**Comment by mrtazz** [comment]
ooh good catch, I think that got lost in the transition to [Travis trusty](https://github.com/mrtazz/restclient-cpp/pull/66). I'll add that back in.

**Comment by mrtazz** [comment]
@bl4ck5un ok master is updated and should install the correct libcurl version

**Comment by bl4ck5un** [comment]
@mrtazz Great. Now CI passes. I seems good to merge.

**Comment by mrtazz** [comment]
awesome! thanks for the contribution

**Pull request closed without merging**
