### PR TITLE
write callback and termination API

### PR DESCRIPTION
**Pull request by edwinpjacques**
# Description

1. Allow write callback.  Application was to use it to leverage the Kubernetes watch API which maintains a long-running connection.
1. API to terminate connection from another thread.
1. Fix all the disabled/broken CI tests that block the merge.

## Checklist
Not all of these might apply to your change but the more you are able to check
the easier it will be to get your contribution merged.

- [X] CI passes
- [X] Description of proposed change
- [X] Documentation (README, code doc blocks, etc) is updated
- [X] Existing issue is referenced if there is one
    - #162 write callback support
    - #161 CI does not work locally
- [X] Unit tests for the proposed change

### CODE REVIEW

**Comment by edwinpjacques** [comment]
@mrtazz I am ready for your review, and hopefully your approval!  I did a lot of work to get the CI working well again.  I enabled all tests, even the OPTIONS test.  I would very much appreciate if this can be approved, or if you can provide any necessary feedback for approval ASAP.  Thank you.

**Comment by edwinpjacques** [comment]
Just updated some documentation and removed an unneeded file I added.

**Comment by edwinpjacques** [comment]
@shawkinsl would you be able to provide any feedback on this merge request?  It fixes CI and allows for stream processing of a GET response via write callback.

**Review by edwinpjacques — COMMENTED** [review]
squashed commits, ready for approval.

**Comment by edwinpjacques** [comment]
@ElonDusk26 and @KaiPetzke would you mind to give a "thumbs up" on this review so I can get it merged with a clean conscience?  Thanks!

**Comment by ElonDusk26** [comment]
Astounding work @edwinpjacques! Hopefully @mrtazz agrees with me.

**Comment by edwinpjacques** [comment]
Got out-of-band permission to merge from @mrtazz based on trust.  Thanks for the kudos @ElonDusk26 !  I hope you can help fix the issue #158.  It would be nice to have that resolved in the next release of code.  Thank you.

**Comment by KaiPetzke** [comment]
Sorry to disagree on this one. The callback declaration:

    auto writeCallback = [](void *data, size_t size, size_t nmemb, void *userdata) -> size_t

looks too much old-style C-ish to me. This is a C++ wrapper around libcurl, and we should use C++ APIs, not C APIs.

The C++11 style would be to use `std::function`.

The Pre-C++11-style would be to use a class with a virtual function `callback`

**Pull request merged**
