### PR TITLE
timeout for whole rest operations

### PR DESCRIPTION
**Pull request by 69736c616d**
here is the simple patch for timeout.

### CODE REVIEW

**Comment by mrtazz** [comment]
thank you for submitting this pull request and sorry for the wait. Could you remove the DS_Store files and add some unit tests around the functionality so I don't accidentally break it in future commits?

**Comment by mrtazz** [comment]
Sorry for the delay here. I just changed the tests for running against httpbin. Would you mind merging master into your pull request and writing a test to run against http://httpbin.org/delay/10 or something with the right timeout settings?

**Comment by 69736c616d** [comment]
ok, i will check out that.

Greetings
iyasar

**Comment by 69736c616d** [comment]
corrected code where test cases fail.

**Comment by 69736c616d** [comment]
checking other issues,

**Comment by 69736c616d** [comment]
i think, it is done

**Comment by mrtazz** [comment]
@69736c616d thanks for the quick update! I would still love to have some tests for the new functionality against the httpbin endpoint I mentioned. This is important for two reasons:

1. I don't want to accidentally break functionality in the future
2. There should be a documented way of how to use it

The tests provide both of those things. For extra bonus points, some documentation in the README would be great.

**Comment by 69736c616d** [comment]
@mrtazz  http://httpbin.org/delay/10 is not suitable for delete, post and put operation. Therefore im getting 405 from server. Can you suggest any other url ?

**Comment by mrtazz** [comment]
Ugh I remember there being an open issue to allow the route for all methods. In that case I think it's ok to only have the test for GET for now. And I'll keep an eye on httpbin to see if they implement that.

**Comment by mrtazz** [comment]
I just updated the unit test suite in master to also support JSON parsing  (https://github.com/mrtazz/restclient-cpp/pull/25). So if you merge from master you should also be able to parse the JSON output you get back from httpbin

**Comment by mrtazz** [comment]
Thanks for taking the time to fixing this up! Looking good now!

**Pull request merged**
